spring:
  application:
    name: resource-service
server:
  port: 8886
  servlet:
    context-path: resource-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/dev-realm
